### PR TITLE
warn users about upgrades in the confirm text

### PR DESCRIPTION
**Pull request by tcrayford**
tell them "we're going to restart nodes" before they actually start that

### CODE REVIEW

**Comment by jkakar** [comment]
Looks good.  The only thought I have is that the log lines emitted once the upgrade starts say the same thing, so you might want to drop lines 35-37 in that file.

**Comment by idan** [comment]
(From DUX sync): This duplicates some of the text that's already in shogun. Not sure why we're doing that. @uhoh-itsmaciek to follow up with @tcrayford. Where is the onus of control when it comes to error messages — ensuring consistency between DHC and CLIs.

**Comment by uhoh-itsmaciek** [comment]
@idan @rand ok, so the issue here is that we currently don't warn users that an upgrade will trigger a rolling restart; I *think* I was wrong about duplicating info that comes from the upgrade request.  Tom's second commit here fixes the duplication issue @jkakar initially mentioned. I want to confirm how this looks with the actual Shogun upgrade output, but other than that, I think this is a solid change.

**Comment by uhoh-itsmaciek** [comment]
+1

**Comment by tcrayford** [comment]
@uhoh-itsmaciek it looks like this, roughly:

```
 ▸    This command will upgrade the brokers of the cluster to version 0.10.
 ▸    Upgrading the cluster involves rolling restarts of brokers, and takes some time, depending on the
 ▸    size of the cluster.
 ▸    To proceed, type infinite-castle-2207 or re-run this command with --confirm infinite-castle-2207

> infinite-castle-2207
Uprading kafka-tcrayford-closed-11972 to version 0.10...started

Use `heroku kafka:wait` to monitor the upgrade.
```

**Pull request merged**
