### PR TITLE
Improve kafka:topics:retention-time description and help

### PR DESCRIPTION
**Pull request by uhoh-itsmaciek**

### CODE REVIEW

**Comment by uhoh-itsmaciek** [comment]
Fixes #99.

**Comment by fnando** [comment]
Were the docs completely wrong before or is this PR missing the companion code?

**Comment by uhoh-itsmaciek** [comment]
Neither. Both syntaxes are supported, but I thought I'd stick with the simpler one in the examples and description.

**Comment by idan** [comment]
Nice.

👍

**Pull request merged**
