### PR TITLE
remove jmx command

### PR DESCRIPTION
**Pull request by justindowning**
The corresponding endpoint does not exist.

### CODE REVIEW

**Comment by uhoh-itsmaciek** [comment]
The command is hidden. Is the endpoint never going to exist? It was originally planned to exist shortly after we added the command.

**Comment by idan** [comment]
@thody to follow up with Justin about what this means

**Comment by thody** [comment]
+1

**Comment by thody** [comment]
@heroku/dod-ux for context, this command was intended to toggle JMX access after provision time, but it was never implemented API-side (casualty of some pre-GA scope cutting). There's little likelihood that we'll implement this, so just cleaning up dead code here.

**Comment by uhoh-itsmaciek** [comment]
Cool, thanks for following up.

**Pull request merged**
