### PR TITLE
add support for displaying prefix

### PR DESCRIPTION
**Pull request by justindowning**

### CODE REVIEW

**Comment by uhoh-itsmaciek** [comment]
Why a separate command instead of just using `:info`?

**Comment by justindowning** [comment]
Just seemed like a nice shortcut for a user to get a machine-readable string without having to parse the entire info payload.

**Comment by uhoh-itsmaciek** [comment]
Ah, I see. But if the goal is automation, maybe we should add a `--json` output to `:info` instead? I'm wary of bloating the `kafka:` namespace, especially since this command is useless on ST plans (in fact, maybe we should fail more obviously than "no prefix found" if we decide to go this route).

**Comment by justindowning** [comment]
No problem. I dropped the `:prefix` command here. We can revisit alternative outputs for commands like `:info` in the future.

**Comment by uhoh-itsmaciek** [comment]
Ok, great. If you'd like, you can push the old commit before you dropped it to another branch so we have it around if we want to revisit.

+1

**Pull request merged**
