### PR TITLE
Cleaner error handling for kafka:tail

### PR DESCRIPTION
**Pull request by uhoh-itsmaciek**

### CODE REVIEW

**Comment by uhoh-itsmaciek** [comment]
It looks like the way subscribe works, we'll still get errors on non-existent topics using this:

```console
maciek@mothra:~/code/aux/heroku-kafka-jsplugin$ h kafka:tail foo --app maru-maciek
Unhandled rejection KafkaError: UnknownTopicOrPartition: This request is for a topic or partition that does not exist on this broker.
```

**Comment by fnando** [comment]
Looks good (seems just like a `try..catch` wrapping.) 

Do you think that error message is readable enough or should we catch that specific error and display a proper message?

Other that that, 👍.

**Comment by uhoh-itsmaciek** [comment]
I don't really know how to catch that: the error seems to be happening inside subscribe somehow since the command still hangs. It's something to fix but I think this doesn't make it any worse, so we can consider that a separate issue and fix it separately.

**Comment by fnando** [comment]
:shipit: as it is. 👍

**Pull request merged**
